const ITEM_DETAILS = {
  'dirt': ['Dirt', 'Can be placed'],
  'wood': ['Wood', 'Can be placed'],
  'gold': ['Gold', 'Can be placed'],
  'silver': ['Silver', 'Can be placed'],
  'wooden_sword': ['Wooden Sword', 'Damage: 7'],
  'silver_sword': ['Silver Sword', 'Damage: 9'],
  'silver_pick': ['Silver Pickaxe', 'Pick Power: 2'],
  'silver_axe': ['Silver Axe', 'Axe Power: 2'],
  'silver_helm': ['Silver Helmet', 'Armor: 3'],
  'silver_chest': ['Silver Chest', 'Armor: 3'],
  'silver_boot': ['Silver Boots', 'Armor: 3'],
  'gold_sword': ['Gold Sword', 'Damage: 15'],
  'gold_pick': ['Gold Pickaxe', 'Pick Power: 4'],
  'gold_axe': ['Gold Axe', 'Axe Power: 4'],
  'gold_helm': ['Gold Helmet', 'Armor: 5'],
  'gold_chest': ['Gold Chest', 'Armor: 5'],
  'gold_boot': ['Gold Boots', 'Armor: 5'],
  'gold_bar': ['Gold Bar'],
  'silver_bar': ['Silver Bar'],
  'cloud': ['Cloud in a Bottle', 'Allows double jump'],
  'rocket': ['Rocket Boot', 'Allows flight for a short time'],
  'fire_sword': ['Fire Staff', 'Can throw fireball', 'Damage: 10', 'Mana Cost: 20'],
  'lens': ['Lens'],
  'zombie_drop': ['Zombie Part'],
  'gel': ['Gel']
}