const CRAFTING_MATERIAL = {
  0: [['silver_bar', 3]],
  1: [['silver_bar', 2], ['wood', 2]],
  2: [['silver_bar', 2], ['wood', 2]],
  3: [['silver_bar', 4]],
  4: [['silver_bar', 4]],
  5: [['silver_bar', 4]],
  6: [['gold_bar', 3]],
  7: [['gold_bar', 2], ['wood', 2]],
  8: [['gold_bar', 2], ['wood', 2]],
  9: [['gold_bar', 4]],
  10: [['gold_bar', 4]],
  11: [['gold_bar', 4]],
  12: [['gold', 1]],
  13: [['silver', 1]],
  14: [['gel', 5], ['lens', 5]],
}

const CRAFT_ITEM = {
  0: 'silver_sword',
  1: 'silver_pick',
  2: 'silver_axe',
  3: 'silver_helm',
  4: 'silver_chest',
  5: 'silver_boot',
  6: 'gold_sword',
  7: 'gold_pick',
  8: 'gold_axe',
  9: 'gold_helm',
  10: 'gold_chest',
  11: 'gold_boot',
  12: 'gold_bar',
  13: 'silver_bar',
  14: 'cloud',
}